# YOU CAN CHANGE THESE:
STREAM_KEY_LENGTH = 16
PING_INTERVAL = 5.
PONG_RESPONSE_LENGTH = 5
STATUS_MESSAGE_LENGTH = 4
MASTER_HANDSHAKE_MESSAGE_LENGTH = 8
TUNNEL_ID_LENGTH = 16
TUNNEL_TIMEOUT = 10.
BUFFER_SIZE = 1024
SECRET_LENGTH = 16
REQUEST_MESSAGE_LENGTH = 4
# DO NOT CHANGE THIS:
RSA_KEY_LENGTH = (max(STREAM_KEY_LENGTH, MASTER_HANDSHAKE_MESSAGE_LENGTH) + 11) * 8
