# b'\xC0\xCA\xC0\x1A' -> COCA COLA
# b'\xBA\xBE\xBA\xBE' -> BABE BABE
# b'\xFE\xCA\x1E\x1F' -> FECAL ELF
# b'\xEC\x0B\xA1\x12' -> ECO BALLZ

# MASTER
MASTER_SIGNAL = b'\xF0\xCC\xBA\xBE'  # FOCC BABE

# TUNNEL
TUNNEL_SIGNAL = b'\xFE\xCA\x1E\x1F'  # FECAL ELF

# HANDSHAKE
HANDSHAKE_SUCCESS = b'\x00\x00\x00\x00'
HANDSHAKE_FAILURE = b'\xFF\xFF\xFF\xFF'
